package ru.stqa.pft.addressbook;

// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.stqa.pft.addressbook.testData.GroupData;
import ru.stqa.pft.addressbook.testData.NewNoteData;

import java.time.Duration;
import java.util.*;

/**
 * Класс для тестирования создания групп в БД addressbook
 * Ответственный за создание класса - А.А. Дюжаков
 * Дата создания - 24.02.2022
 */

public class GroupCreationTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
//    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS); // is deprecated
        new WebDriverWait(driver, Duration.ofSeconds(60));
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.get("http://localhost/addressbook/");
        authorization("admin", "secret");
    }

    @Test
    public void groupCreationTest() {

        String groupPageXpath = "//div[@id=\"nav\"]//a[.='groups']";
        String returnGroupPageXpath = "//a[.='group page']";
        String creationGroupName = "new";
        String nameGroupXpath = "group_name";
        String headerGroupXpath = "group_header";
        String footerGroupXpath = "group_footer";
        String buttonNameXpath = "submit";
        GroupData groupData = new GroupData("TestGroup", "Test group header", "Test group footer");

        goToPage(groupPageXpath);
        initGroupCreation(creationGroupName);
        fillGroupForm(nameGroupXpath, headerGroupXpath, footerGroupXpath, buttonNameXpath, groupData);
        goToPage(returnGroupPageXpath);
    }

    @Test
    public void addNewTest() {

        // Тестовые данные
        String addNewPageXpath = "//a[.='add new']";
        String buttonXpath = "//div[@id=\"content\"]//*[@type=\"submit\"][1]";
        String firstName = "Boris";
        String lastName = "Ivanov";
        String address = "Moscow";
        String email = "email@mail.ts";
        String mobileFone = "+79991231212";

        NewNoteData newNoteData = new NewNoteData(firstName, lastName, address, email, mobileFone);

        goToPage(addNewPageXpath);
        fillAddNewNoteForm(newNoteData);
        saveData(buttonXpath);
    }

    @AfterMethod
    public void tearDown() {
        driver.quit();
    }

    // Метод авторизации в БД
    private void authorization(String userName, String password) {

        String mainPageXpath = "//input[@type=\"submit\"]";

        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.name("user")).click();
        driver.findElement(By.name("user")).sendKeys(userName);
        driver.findElement(By.name("pass")).click();
        driver.findElement(By.name("pass")).sendKeys(password);
        goToPage(mainPageXpath);
    }

    // Метод заполнения полей новой группы
    private void fillGroupForm(String name, String header, String footer, String button, GroupData groupData) {
        driver.findElement(By.name(name)).click();
        driver.findElement(By.name(name)).sendKeys(groupData.getNameGroup());
        driver.findElement(By.name(header)).click();
        driver.findElement(By.name(header)).sendKeys(groupData.getHeaderGroup());
        driver.findElement(By.name(footer)).click();
        driver.findElement(By.name(footer)).sendKeys(groupData.getFooterGroup());
        driver.findElement(By.name(button)).click();
    }

    // Метод создания новой группы
    private void initGroupCreation(String s) {
        driver.findElement(By.name(s)).click();
    }

    // Метод заполнения полей новой записи в БД
    private void fillAddNewNoteForm(NewNoteData newNoteData) {

        driver.findElement(By.name(newNoteData.getFIRST_NAME_XPATH())).sendKeys(newNoteData.getFirstName());
        driver.findElement(By.name(newNoteData.getLAST_NAME_XPATH())).sendKeys(newNoteData.getLastName());
        driver.findElement(By.name(newNoteData.getADDRESS_XPATH())).sendKeys(newNoteData.getAddress());
        driver.findElement(By.name(newNoteData.getEMAIL_XPATH())).sendKeys(newNoteData.getEmail());
        driver.findElement(By.name(newNoteData.getMOBILE_PHONE_XPATH())).sendKeys(newNoteData.getMobileFone());
    }

    // Метод перехода на страницу
    private void goToPage(String s) {
        driver.findElement(By.xpath(s)).click();
    }

    // Метод сохранения данных в БД
    private void saveData(String s) {
        driver.findElement(By.xpath(s)).click();
    }
}
