package ru.stqa.pft.addressbook;

// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class GroupCreationTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeMethod
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
//    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS); // is deprecated
    new WebDriverWait(driver, Duration.ofSeconds(60));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @Test
  public void untitled() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.name("user")).click();
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).click();
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.cssSelector("input:nth-child(1)")).click(); // (!!! разобраться с кодом)
    driver.findElement(By.cssSelector(".admin font > font")).click();
    driver.findElement(By.name("new")).click();
    driver.findElement(By.name("group_name")).click();
    driver.findElement(By.name("group_name")).sendKeys("TestGroup");
    driver.findElement(By.name("group_header")).click();
    driver.findElement(By.name("group_header")).click();
    driver.findElement(By.name("group_header")).sendKeys("Test group header");
    driver.findElement(By.name("group_footer")).click();
    driver.findElement(By.name("group_footer")).sendKeys("Test group footer");
    driver.findElement(By.name("submit")).click();
    driver.findElement(By.cssSelector("i > a > font > font")).click();
  }

  @AfterMethod
  public void tearDown() {
    driver.quit();
  }
}
